### PR TITLE
Add support for twemoji.

### PR DESCRIPTION
**Pull request by toolstack**
Converts emoji to images on browsers that don't have proper emoji support.

### CODE REVIEW

**Comment by nerzhul** [comment]
i don't like the external URL dependency. Can you embed the files in the repository ? Don't forget ocsms has sensible informations (in URL too unfortunately), leaking them to an external CDN is not a good thing.

**Comment by toolstack** [comment]
It could be, but twemoji is relativly large (due to the emoji graphic files) and requires some customization to be used locally.

What do yiu think of including the script locally but leaving the cdn for the image files?

**Comment by nerzhul** [comment]
you will have the same problem due to the referer. The graphic file is not a map ? it's one file per icon ?

**Comment by toolstack** [comment]
Yes, though it's really 2 per emoji as they support both png and svg versions.

I'll create a second PR with it implemented locally so you can see the difference.

**Comment by toolstack** [comment]
I've created the second pull request, it adds about 13mb of files to the app.

**Comment by toolstack** [comment]
Hi @nerzhul, have you had a chance to look at this PR as well as #254?

**Comment by toolstack** [comment]
Closing in favour of local support.

**Pull request closed without merging**
