### PR TITLE
Fix the display of the SMS bubbles

### LINKED ISSUE #238: SMS no longer display in "bubles"
### Steps to reproduce
1. Open a conversation
2. 
3.

### Expected behaviour
Messages should be displayed in coloured bubles, correspondant's on the left mine on the right
(like on the Phone Sync documentation)
### Actual behaviour
Messages are displayed on a basic list.
No way to tell which ones are mine and which ones are my correspondant's.

### Server configuration

**Nextcloud/ownCloud version: NC 13.0.2**
**Phone Sync version: 1.12.7

**PHP version: 7.1.3**

**HTTPd server: apache**

**Database engine & version:** MariaDB 10.0 

### Client configuration

**Android version:**

**Phone:**

**Nextcloud SMS app version:**

### Logs
no log
```
Insert your log here
```

### PR DESCRIPTION
**Pull request by Idix**
Also add a fallback CSS class
Fixes #238

### CODE REVIEW

**Comment by nerzhul** [comment]
Hello, thanks for the fix. You should not update app.min.js yourself, it's updated by the repository owners. The only change is on legacy.js ?

**Comment by Idix** [comment]
Hi, I've removed the commit on app.min.js. Yes the change is only on legacy.js.

**Comment by nerzhul** [comment]
thanks, merging

**Comment by X-dark** [comment]
I still have the bug after the last update but I do not see the change in app.min.js.

**Comment by Idix** [comment]
@X-dark, yes the app.min.js needs to be rebuilt.

As a temporary fix, you can apply the following patch, open file **templates/main.php**

Replace the line
`\OCP\Util::addScript('ocsms', 'app.min');`

With the following lines
```
\OCP\Util::addScript('ocsms', 'devel/legacy');
\OCP\Util::addScript('ocsms', 'devel/notifications');
\OCP\Util::addScript('ocsms', 'devel/app');
\OCP\Util::addScript('ocsms', 'devel/helpers');
\OCP\Util::addScript('ocsms', 'devel/settings');
```
After this you, won't use the minified file anymore.

**Comment by nerzhul** [comment]
oops i forgot this was updated... i will fix it

**Comment by nerzhul** [comment]
@Idix 1.13.1 updated with JS fix

**Pull request merged**
